config/routes.rb
Rails.application.routes.draw do
  root to: 'manifests#index'
  resources :manifests, only: [:new, :create, :show, :index]

  resources :manifests, only: [:show] do
    resources :sign_or_upload, only: [:new]
    resources :manifest_uploads, only: [:new, :create, :show]
    resources :signatures, only: [:new, :create]
    get 'signature', to: 'signatures#show'
    resources :tokens, only: [:new, :create]
  end

  resources :manifest_uploads, only: [:new, :create]
  resources :submissions, only: [:new]

  get 'login', to: 'auth#new'
  post 'login', to: 'auth#login'
  get 'logout', to: 'auth#logout'
  get 'profile', to: 'auth#profile'

  get 'api-examples', to: 'api_documentation#examples'
  get 'api-diagnostics', to: 'api_documentation#diagnostics'
  get 'api-documentation', to: 'api_documentation#swagger'

  namespace :api do
    namespace :v0 do
      resources :tokens, only: [:create]
      get 'manifests/search', to: 'manifests#search'
      post 'manifests/validate', to: 'manifests#validate'
      resources :manifests, only: [:create, :show, :update] do
        resource :signature, only: [:create]
      end
      resources :method_codes, only: [:index]
    end
  end

  require 'sidekiq/web'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV['SIDEKIQ_USERNAME'] && password == ENV['SIDEKIQ_PASSWORD']
  end

  mount Sidekiq::Web => '/sidekiq'
end

app/controllers/sign_or_upload_controller.rb
class SignOrUploadController < ApplicationController
  def new
    @manifest = Manifest.find_by_uuid_or_tracking_number!(params[:manifest_id])
  end
end

app/views/sign_or_upload/new.html.erb
<div class="usa-width-one-whole">

  <h3>Sign or Upload</h3>

  <p>
    Would you like to electronically sign this manifest (CDX login required) or
    would you like to upload a scan of the original manifest?
  </p>

  <%= link_to 'Sign', new_manifest_token_path(@manifest.uuid), class: 'usa-button' %>
  <%= link_to 'Upload', new_manifest_manifest_upload_path(@manifest.uuid), class: 'usa-button usa-button-outline' %>
</div>