config/routes.rb
Rails.application.routes.draw do
  root to: 'manifests#index'
  resources :manifests, only: [:new, :create, :show, :index]

  resources :manifests, only: [:show] do
    resources :sign_or_upload, only: [:new]
    resources :manifest_uploads, only: [:new, :create, :show]
    resources :signatures, only: [:new, :create]
    get 'signature', to: 'signatures#show'
    resources :tokens, only: [:new, :create]
  end

  resources :manifest_uploads, only: [:new, :create]
  resources :submissions, only: [:new]

  get 'login', to: 'auth#new'
  post 'login', to: 'auth#login'
  get 'logout', to: 'auth#logout'
  get 'profile', to: 'auth#profile'

  get 'api-examples', to: 'api_documentation#examples'
  get 'api-diagnostics', to: 'api_documentation#diagnostics'
  get 'api-documentation', to: 'api_documentation#swagger'

  namespace :api do
    namespace :v0 do
      resources :tokens, only: [:create]
      get 'manifests/search', to: 'manifests#search'
      post 'manifests/validate', to: 'manifests#validate'
      resources :manifests, only: [:create, :show, :update] do
        resource :signature, only: [:create]
      end
      resources :method_codes, only: [:index]
    end
  end

  require 'sidekiq/web'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV['SIDEKIQ_USERNAME'] && password == ENV['SIDEKIQ_PASSWORD']
  end

  mount Sidekiq::Web => '/sidekiq'
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  def new

  end
end

app/views/submissions/new.html.erb
<div class="usa-width-one-whole">

  <h3>DEMONSTRATION PAGE DISCLAIMER </h3>
  <p>This page is only for demonstrations provided by EPA.  EPA is building and providing its services for states and the regulated community to consume first.  At a later time once our services have been built and we have received feedback from states and industry on them, we will build graphical user interfaces for users with input from users that will use those interfaces.</p>
  <h3>DEMONSTRATION PAGE DISCLAIMER </h3>

  <h3>Submit a manifest</h3>

  <%= link_to 'Submit via form', new_manifest_path, class: 'usa-button' %>
  <%= link_to 'Upload scan', new_manifest_upload_path, class: 'usa-button usa-button-outline' %>
</div>