config/routes.rb
Rails.application.routes.draw do
  root to: 'manifests#index'
  resources :manifests, only: [:new, :create, :show, :index]

  resources :manifests, only: [:show] do
    resources :sign_or_upload, only: [:new]
    resources :manifest_uploads, only: [:new, :create, :show]
    resources :signatures, only: [:new, :create]
    get 'signature', to: 'signatures#show'
    resources :tokens, only: [:new, :create]
  end

  resources :manifest_uploads, only: [:new, :create]
  resources :submissions, only: [:new]

  get 'login', to: 'auth#new'
  post 'login', to: 'auth#login'
  get 'logout', to: 'auth#logout'
  get 'profile', to: 'auth#profile'

  get 'api-examples', to: 'api_documentation#examples'
  get 'api-diagnostics', to: 'api_documentation#diagnostics'
  get 'api-documentation', to: 'api_documentation#swagger'

  namespace :api do
    namespace :v0 do
      resources :tokens, only: [:create]
      get 'manifests/search', to: 'manifests#search'
      post 'manifests/validate', to: 'manifests#validate'
      resources :manifests, only: [:create, :show, :update] do
        resource :signature, only: [:create]
      end
      resources :method_codes, only: [:index]
    end
  end

  require 'sidekiq/web'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV['SIDEKIQ_USERNAME'] && password == ENV['SIDEKIQ_PASSWORD']
  end

  mount Sidekiq::Web => '/sidekiq'
end

app/models/cdx/manifest.rb
class CDX::Manifest
  attr_reader :opts, :output_stream

  def initialize(opts, output_stream=$stdout)
    @opts = opts
    @output_stream = output_stream
  end

  def submit
    validate_answer
    repackage_response
  rescue Savon::SOAPFault => error
    log_and_repackage_error(error)
  end

  private

  def validate_answer
    @_answer ||= CDX::Answer.new(opts, output_stream).perform
  end

  def repackage_response
    if validate_answer == true
      { transaction_id: transaction_id }
    else
      validate_answer
    end
  end

  def transaction_id
    @transaction_id ||= CDX::Sign.new(opts, output_stream).perform
  end

  def log_and_repackage_error(error)
    CDX::HandleError.new(error, output_stream).perform
  end
end

app/models/manifest.rb
require 'date'

class Manifest < ActiveRecord::Base
  include Searchable

  validate :tracking_number, :validate_tracking_number_unique
  validates :user_id, presence: true
  belongs_to :user, class_name: 'User'

  # Elasticsearch configuration
  settings index: {
    number_of_shards: 1, # increase this if we ever get more than N records
    number_of_replicas: 1
  } do
    # with dynamic mapping==true, we only need to explicitly define overrides.
    # https://www.elastic.co/guide/en/elasticsearch/guide/current/dynamic-mapping.html
    mappings dynamic: "true" do
      indexes :content do
        indexes :generator do
          indexes :signatory do
            indexes :date, type: "string"
          end
        end
        indexes :transporters do
          indexes :signatory do
            indexes :date, type: "string"
          end
        end
        indexes :designated_facility do
          indexes :certification do
            indexes :date, type: "string"
          end
          indexes :discrepancy do
            indexes :signatory do
              indexes :date, type: "string"
            end
          end
        end
        indexes :international_shipment do
          indexes :port_of_entry_exit do
            indexes :city, type: "string"
            indexes :state, type: "string"
          end
        end
      end
    end
  end

  def self.state_fields
    [
      'generator.mailing_address.state',
      'generator.site_address.state',
      'international_shipment.port_of_entry_exit.state',
      'designated_facility.address.state',
      'designated_facility.discrepancy.address.state'
    ]
  end

  def has_state?(state)
    self.class.state_fields.select do |state_field|
      state_value = content_field(state_field)
      state_value == state
    end.any?
  end

  def content_field(json_xpath)
    fields = json_xpath.split('.')
    if content && fields.inject(content) { |h,k| h[k] if h }
      fields.inject(content) { |h,k| h[k] if h }
    end
  end

  def tracking_number
    content_field('generator.manifest_tracking_number')
  end

  def generator_name
    content_field('generator.name') || ''
  end

  def disposal_facility
    content_field('generator.disposal_facility.name')
  end

  def created_on
    created_at.strftime('%m/%d/%Y')
  end

  def generator_emergency_response_phone
    content_field('generator.emergency_response_phone')
  end

  def generator_phone_number
    content_field('generator.phone_number')
  end

  def generator_mailing_address
    content_field('generator.mailing_address') || {}
  end

  def transporters
    content_field('transporters') || []
  end

  def designated_facility
    content_field('designated_facility') || {}
  end

  def designated_facility_address
    content_field('designated_facility.address') || {}
  end

  def designated_facility_name
    content_field('designated_facility.name')
  end

  def international
  end

  def designated_facility_signed_date
    content_field('designated_facility.certification') || ''
  end

  def manifest_items
    content_field('manifest_items') || []
  end

  def waste_handling_instructions
    content_field('waste_handling_instructions')
  end

  def waste_pcb_description
    content_field('waste_pcb_description')
  end

  def waste_report_codes
    content_field('report_management_method_codes') || []
  end

  def handler_defined
    content_field('handler_defined_data') || []
  end

  def self.find_by_uuid_or_tracking_number(id)
    find_by(uuid: id) || find_by_tracking_number(id)
  end

  def self.find_by_tracking_number(tracking_number)
    find_by("content -> 'generator' ->> 'manifest_tracking_number' = ?", tracking_number.to_s)
  end

  def self.find_by_uuid_or_tracking_number!(id)
    find_by_uuid_or_tracking_number(id) or raise ManifestNotFound.new "Could not find #{id} by uuid or tracking_number"
  end

  def self.authorized_search(params, user=nil)
    dsl = Search::QueryDSL.new(params: params, user: user)
    resp = search(dsl)
    { es_response: resp, dsl: dsl }
  end

  def is_public?
    created_at < 90.days.ago
  end

  private

  def validate_tracking_number_unique
    if tracking_number.blank?
      errors.add(:tracking_number, "must be present")
    elsif tracking_number !~ /^[0-9]{9}[A-Za-z]{3}$/
      errors.add(:tracking_number, "must be 12 characters, starting with 9 numbers and ending with 3 letters")
    elsif tracking_number_already_exists?
      errors.add(:tracking_number, "must be unique")
    elsif exists_with_different_tracking_number?
      errors.add(:tracking_number, "must be unique")
    end
  end

  def tracking_number_already_exists?
    !id && Manifest.find_by_tracking_number(tracking_number)
  end

  def exists_with_different_tracking_number?
    existing = Manifest.find_by_tracking_number(tracking_number)
    id && existing && existing.id != id
  end
end

app/controllers/api/v0/manifests_controller.rb
class Api::V0::ManifestsController < ApiController
  include SearchParams

  rescue_from ActiveRecord::RecordNotFound, with: :manifest_not_found_error

  def search
    if !params[:q] && !params[:aq]
      render json: {message: 'Missing q or aq param'}, status: 400
    else
      render json: ManifestSearchSerializer.new(Manifest.authorized_search(params)[:es_response]).to_json
    end
  end

  def validate
    manifest_content = read_body_as_json
    unless performed?
      if validate_manifest(manifest_content)
        render json: {message: "Manifest structure is valid"}, status: 200
      end
    end
  end

  def create
    authenticate_user!
    unless performed?
      manifest_content = read_body_as_json
    end

    unless performed?
      if validate_manifest(manifest_content)
        @manifest = Manifest.new(content: manifest_content, user: current_user)
        authorize @manifest, :can_create?
        create_manifest(@manifest)
      end
    end
  end

  def show
    manifest = find_manifest
    if has_permission_to_view?(manifest)
      unless performed?
        render json: ManifestSerializer.new(manifest).to_json
      end
    else
      unless performed?
        render json: {
          message: "Permission denied",
          errors: "You do not have permission to view this manifest."
        }, status: 403
      end
    end
  end

  def update
    manifest = find_manifest
    if has_permission_to_update?(manifest)
      if (patch = read_body_as_json)
        patch_json = patch.to_json
        manifest_content_json = manifest[:content].to_json
        new_json = JSON.patch(manifest_content_json, patch_json)

        manifest.update_column(:content, new_json)

        render json: ManifestSerializer.new(manifest).to_json
      end
    else
      render json: {
        message: "Permission denied",
        errors: "You do not have permission to update this manifest."
      }, status: 403
    end
  end

  private

  def create_manifest(manifest)
    if manifest.save
      manifest.reload
      render json: {
        message: "Manifest #{manifest.tracking_number} submitted successfully.",
        location: api_v0_manifest_url(manifest.uuid)
      }, status: 201
    else
      render json: {
        message: "Validation failed",
        errors: manifest.errors.full_messages.to_sentence
      }, status: 422
    end
  end

  def validate_manifest(content)
    run_validator(ManifestValidator.new(content))
  end

  def has_permission_to_update?(manifest)
    if !authenticated?
      false
    else
      authorize manifest, :can_update?
    end
  end

  def has_permission_to_view?(manifest)
    if manifest.is_public?
      true
    elsif authenticated?
      authorize manifest, :can_view?
    else
      false
    end
  end
end

app/controllers/manifests_controller.rb
class ManifestsController < ApplicationController
  include ManifestParams
  include SearchParams

  def new
    authenticate_user!
    unless performed?
      authorize Manifest.new, :can_create?
    end
  end

  def create
    authenticate_user!

    unless performed?
      @manifest = Manifest.new(content: manifest_params, user: current_user)

      authorize @manifest, :can_create?

      if @manifest.valid? && validate_manifest(manifest_params)
        create_manifest
      else
        flash[:error] = error_messages
        render :new
      end
    end
  end

  def index
    if !authenticated? || !has_search_params?
      params.merge!({public: true})
    end
    @search_response = Manifest.authorized_search(params, current_user)
    @es_response = @search_response[:es_response]
    @manifests = @es_response.records.to_a
    build_search_stats
  end

  def show
    @manifest = Manifest.find_by_uuid_or_tracking_number!(params[:id])
    has_permission? or return
  end

  private

  def create_manifest
    @manifest.save!
    @manifest.reload
    flash[:notice] = "Manifest #{@manifest.tracking_number} submitted successfully."
    redirect_to new_manifest_sign_or_upload_path(@manifest.uuid)
  end

  def has_permission?
    if !@manifest.is_public?
      authenticate_user!

      unless performed?
        authorize @manifest, :can_view?
      end
    end
    true
  end

  def validate_manifest(content)
    validator = ManifestValidator.new(content)
    unless validator.run
      @errors = validator.error_messages
    end
    !validator.errors.any?
  end

  def error_messages
    [[@errors] + [@manifest.errors.full_messages]].flatten.compact.to_sentence
  end

  def build_search_stats
    dsl_hash = @search_response[:dsl].to_hash
    @stats = {
      from: dsl_hash[:from] + 1,
      to: dsl_hash[:from] + dsl_hash[:size],
      total: @search_response[:es_response].results.total,
    }
    if @stats[:total] < dsl_hash[:size]
      @stats[:to] = @stats[:total]
    end
  end
end

app/helpers/manifest_helper.rb
module ManifestHelper
  def file_upload_button(manifest)
    if manifest.content['uploaded_file'].present?
      link_to 'Download Scanned Image', manifest_manifest_upload_path(manifest_id: @manifest.uuid), class: 'usa-button usa-button-outline'
    else
      'No scanned image available for this manifest.'
    end
  end

  def file_uploaded_at(manifest)
    if manifest.content['uploaded_file']['uploaded_at']
      datetime = Time.parse(manifest.content['uploaded_file']['uploaded_at'])
      datetime.strftime('%F %T UTC')
    else
      "unknown"
    end
  end

  def file_uploaded_by(manifest)
    if manifest.content['uploaded_file']['uploaded_by']
      user = User.find( manifest.content['uploaded_file']['uploaded_by'])
      user ? user.cdx_user_id : "unknown"
    else
      "unknown"
    end
  end

  def container_types
    [
      ["BA (Burlap, cloth, paper or plastic bags)", "BA"],
      ["CF (Fiber of plastic boxes, cartons, cases)", "CF"],
      ["CM (Metal boxes, cartons, cases)", "CM"],
      ["CW (Wooden boxes, cartons, cases)", "CW"],
      ["CY (Cylinders)", "CY"],
      ["DF (Fiberbord or plastic drums, barrels, kegs)", "DF"],
      ["DM (Metal drums)", "DM"],
      ["DT (Dump truck)", "DT"],
      ["DW (Wooden drums, barrels, kegs)", "DW"],
      ["HG (Hopper or gondola cars)","HG"],
      ["TC (Tank cars)", "TC"],
      ["TT (Cargo tanks)", "TT"],
      ["TP (Portable tanks)", "TP"]
    ]
  end

  def units_of_measure
    [
      ["Gallons", "G"],
      ["Kilograns", "K"],
      ["Liters", "L"],
      ["Metric tons", "M"],
      ["Cubic Meters", "N"],
      ["Pounds", "P"],
      ["Tons", "T"],
      ["Cubic yards", "Y"]
    ]
  end

  def import_options
    [
      ["Export from U.S.", "export_from_us"],
      ["Import to U.S.", "import_to_us"],
    ]
  end

  def discrepancy_types
    [
      ["No rejection", "no_rejection"],
      ["Partial rejection", "partial_rejection"],
      ["Full rejection", "full_rejection"],
    ]
  end
end

app/views/manifests/_address.html.erb
<%= object.simple_fields_for fields.to_sym do |address| %>
  <%= address.input :address_1, label: "Address 1 (#{number})" %>
  <%= address.input :address_2, label: "Address 2 (#{number})" %>
  <%= address.input :city, label: "City (#{number})" %>
  <%= address.input :state, collection: us_states, label: "State (#{number})" %>
  <%= address.input :zip_code, label: "ZIP code (#{number})" %>
<% end %>

app/views/manifests/_designated_facility.html.erb
<%= form.simple_fields_for :designated_facility do |facility| %>
  <%= facility.input :name, label: 'Name (8)' %>
  <%= render partial: 'address', locals: { fields: 'address', object: facility, number: 8 } %>
  <%= facility.input :phone_number, label: 'Phone number (8)' %>
  <%= facility.input :us_epa_id_number, label: 'U.S. EPA ID Number (8)' %>
  <%= facility.input :shipment_has_discrepancy, as: :radio_buttons, label: 'This shipment has a discrepancy', boolean_style: :inline %>
  <div class="discrepancy">
    <%= facility.simple_fields_for :discrepancy do |discrepancy| %>
      <%= discrepancy.input :description, as: :text, label: "Discrepancy description (18)" %>

      <h4>Discrepancy Indication (18a)</h4>
      <%= discrepancy.input :manifest_tracking_number, label: "New manifest tracking number (18a)" %>
      <%= discrepancy.input :category_quantity, as: :radio_buttons, label: "Discrepancy due to quantity (18a)", boolean_style: :inline %>
      <%= discrepancy.input :category_type, as: :radio_buttons, label: "Discrepancy due to type (18a)", boolean_style: :inline %>
      <%= discrepancy.input :category_residue, as: :radio_buttons, label: "Discrepancy due to residue (18a)", boolean_style: :inline %>
      <%= discrepancy.input :type, as: :select, collection: discrepancy_types, label: "Type of rejection (18a)", boolean_style: :inline %>

      <h4>Alternative facility (or Generator)</h4>
      <%= discrepancy.input :name, label: "Facility name (18b)" %>
      <%= render partial: 'address', locals: { fields: 'address', object: discrepancy, number: '18b' } %>
      <%= discrepancy.input :phone_number, label: "Phone number (18b)" %>
      <%= discrepancy.input :us_epa_id_number, label: "U.S. EPA ID Number (18b)" %>
      <%= discrepancy.simple_fields_for :signatory do |signature| %>
        <%= signature.input :name, label: 'Name of signatory (18c)' %>
        <%= label_tag 'Date of signature (18c)' %>
        <%= date_field_tag 'date', nil, name: "manifest[designated_facility][discrepancy][signatory][date]"  %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/manifests/_manifest_item.html.erb
<div class="manifest-item">
  <h4>Manifest Item 1</h4>
  <%= simple_fields_for :manifest_items do |manifest_item| %>
    <%= manifest_item.input :hazardous_material, label: 'This shipment contains hazardous material (9a)', as: :select, collection: ['True', 'False'], input_html: { class: 'js-manifest-item', name: "manifest[manifest_items][][hazardous_material]", data: { number: '1' } } %>
    <%= manifest_item.input :hazard_classes, label: 'Comma separated hazard classes (9b)', input_html: { name: "manifest[manifest_items][][hazard_classes]" } %>
    <%= manifest_item.input :proper_shipping_name, label: 'Proper shipping name (9b)', input_html: { name: "manifest[manifest_items][][proper_shipping_name]" } %>
    <%= manifest_item.input :id_number, label: 'ID number (9b)', input_html: { name: "manifest[manifest_items][][id_number]" } %>
    <%= manifest_item.input :packing_group, as: :select, collection: ["I", "II", "III"], label: 'Packing group (9b)', input_html: { name: "manifest[manifest_items][][packing_group]" } %>
    <%= manifest_item.input :number_of_containers, as: :integer, label: 'Number of containers (10)', input_html: { name: "manifest[manifest_items][][number_of_containers]" } %>
    <%= manifest_item.input :container_type, as: :select, collection: container_types, label: 'Container type (10)', input_html: { name: "manifest[manifest_items][][container_type]" } %>
    <%= manifest_item.input :total_quantity, as: :integer, label: 'Total quantity for the listed unit of measure (11)', input_html: { name: "manifest[manifest_items][][total_quantity]" } %>
    <%= manifest_item.input :unit_wt_vol, as: :select, collection: units_of_measure, label: 'Unit Wt./Vol. (12)', input_html: { name: "manifest[manifest_items][][unit_wt_vol]" } %>
    <%= manifest_item.input :epa_waste_codes, label: 'Comma separated list of federal waste codes (13)', input_html: { name: "manifest[manifest_items][][epa_waste_codes]" } %>
    <%= manifest_item.input :state_waste_codes, label: 'Comma separated list of state and other waste codes (13)', input_html: { name: "manifest[manifest_items][][state_waste_codes]" } %>
  <% end %>
</div>

app/views/manifests/_transporter.html.erb
<div class="transporter">
  <h4>Transporter 1</h4>
  <%= label_tag :company_name, 'Company name (6)' %>
  <input type='text', name="manifest[transporters][][name]" data-number="1" id="transporter-number">
  <%= label_tag :us_epa_id_number, 'U.S. EPA ID number (6)' %>
  <input type='text', name="manifest[transporters][][us_epa_id_number]">
  <%= label_tag :signatory_name, 'Name of signatory (17)' %>
  <input type='text', name="manifest[transporters][][signatory][name]">
  <%= label_tag :signatory_date, 'Date of signature (17)' %>
  <%= date_field_tag 'date', nil, name: "manifest[transporters][][signatory][date]"  %>
</div>

app/views/manifests/_transporter_fields.html.erb
<div class='nested-fields'>
  <%= f.input :name, label: 'Company Name (6)' %>
  <%= f.input :us_epa_id_number, label: 'U.S. EPA ID Number (6)' %>
  <%= link_to_remove_association "remove transporter", f %>
</div>

app/views/manifests/index.html.erb
<div class="usa-width-two-thirds">

  <h3>Manifests</h3>

  <div class="stats">
    <% if @stats[:total] > 0 %>
    Currently viewing <%= @stats[:from] %>-<%= @stats[:to] %> of <%= number_with_delimiter @stats[:total] %> results.
    <% else %>
    No results
    <% end %>
  </div>

  <table>
    <thead>
      <th>Tracking Number</th>
      <th>Generator Name</th>
      <th>Disposal Facility</th>
      <th>Date</th>
    </thead>
    <tbody>
      <% @manifests.each do |manifest| %>
        <tr>
          <td><%= link_to manifest.tracking_number, manifest_path(manifest.uuid) %></td>
          <td><%= manifest.generator_name %></td>
          <td><%= manifest.disposal_facility %></td>
          <td><%= manifest.created_on %></td>
        </tr>
      <% end %>
      <% if @manifests.length == 0 %>
        <tr>
          <td colspan="4" class="text-center">No records were found that match the criteria.</td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="pager">
    <%= paginate @es_response, current_page: (params[:page]||1).to_i %>
  </div>
</div>

<div class="usa-width-one-third">

  <%= simple_form_for :aq, url: manifests_path, method: :get, html: { class: "callout"} do |form| %>
    <h2>Search  manifests</h2>

    <label class="featured" for="manifest_tracking_number">Manifest Tracking Number</label>
    <input id="manifest_tracking_number" name="aq[content.generator.manifest_tracking_number]" type="text">

    <label class="featured" for="generator_name">Generator name</label>
    <input id="generator_name" name="aq[content.generator.name]" type="text">
    <label class="featured" for="tsdf_name">Disposal facility name</label>
    <input id="tsdf_name" name="aq[content.designated_facility.name]" type="text">

    <div class="usa-grid-full">
      <div class="usa-width-one-half">
        <label for="origin_state">Generator state</label>
        <select name="aq[content.generator.mailing_address.state]" id="origin_state" class="usa-input-grid-tiny tiny-input">
          <option value="">--</option>
          <optgroup label="United States">
            <% us_states.each do |state| %>
             <option value=<%=state[1]%>><%=state[1]%></option>
            <% end %>
          </optgroup>
          <optgroup label="Canadian Provinces">
            <% canadian_provinces.each do |province| %>
             <option value=<%=province[1]%>><%=province[1]%></option>
            <% end %>
          </optgroup>
          <optgroup label="Mexican States">
            <% mexican_states.each do |state| %>
             <option value=<%=state[1]%>><%=state[1]%></option>
            <% end %>
          </optgroup>
        </select>
      </div>
      <div class="usa-width-one-half">
        <label for="disposal_state">Disposal facility state</label>
        <select name="aq[content.designated_facility.address.state]" id="disposal_state" class="tiny-input">
          <option value="">--</option>
          <optgroup label="United States">
            <% us_states.each do |state| %>
             <option value=<%=state[1]%>><%=state[1]%></option>
            <% end %>
          </optgroup>
          <optgroup label="Canadian Provinces">
            <% canadian_provinces.each do |province| %>
             <option value=<%=province[1]%>><%=province[1]%></option>
            <% end %>
          </optgroup>
          <optgroup label="Mexican States">
            <% mexican_states.each do |state| %>
             <option value=<%=state[1]%>><%=state[1]%></option>
            <% end %>
          </optgroup>
        </select>
      </div>
    </div>

    <div class="usa-grid-full">
      <div class="usa-width-one-whole">
        <label for="from_date">Beginning Date</label>
        <input id="from_date" name="aq[created_on]" type="date">
      </div>
      <div class="usa-width-one-whole">
        <label for="to_date">Ending Date</label>
        <input id="to_date" name="to_date" type="date">
      </div>
    </div>

    <label class="featured" for="general">General search</label>
    <input id="general" name="q" type="text">

    <%= form.submit 'Search' %>
    <input type="reset" class="usa-button-outline" value="Clear">
  <% end %>

</div>

app/views/manifests/new.html.erb
<div class="usa-width-one-whole">
  <h3>DEMONSTRATION PAGE DISCLAIMER </h3>
  <p>This page is only for demonstrations provided by EPA.  EPA is building and providing its services for states and the regulated community to consume first.  At a later time once our services have been built and we have received feedback from states and industry on them, we will build graphical user interfaces for users with input from users that will use those interfaces.</p>
  <h3>DEMONSTRATION PAGE DISCLAIMER </h3>

  <h3>Submit new manifest</h3>

  <%= simple_form_for :manifest, url: manifests_path, method: :post do |form| %>
    <fieldset>
      <h3>Generator</h3>
      <%= form.simple_fields_for :generator do |generator| %>
        <%= generator.input :us_epa_id_number, label: 'U.S. EPA ID Number (1)' %>
        <%= generator.input :emergency_response_phone, label: 'Emergency Response Phone (3)' %>
        <%= generator.input :manifest_tracking_number, label: 'Manifest Tracking Number (4)', required: true %>
        <%= generator.input :name, label: 'Name (5)' %>
        <%= generator.simple_fields_for :signatory do |signature| %>
          <%= signature.input :name, label: 'Name of generator/offeror signatory (15)' %>
          <%= label_tag 'Date of signature (15)' %>
          <%= date_field_tag 'date', nil, name: "manifest[generator][signatory][date]"  %>
        <% end %>

        <div class="mailing-address">
          <h3>Mailing address</h3>
          <%= render partial: 'address', locals: { fields: 'mailing_address', object: generator, number: 5 } %>
        </div>

        <%= generator.input :phone_number, label: 'Phone number (5)' %>

        <%= generator.input :site_address_same_as_mailing, as: :radio_buttons, label: 'Site address same as mailing address', boolean_style: :inline %>

        <div class="site-address">
          <h3>Site address</h3>
          <%= render partial: 'address', locals: { fields: 'site_address', object: generator, number: 5 } %>
        </div>
      <% end %>

    </fieldset>

    <fieldset>
      <h3>Transporters</h3>
      <div class="transporters">
        <%= render 'transporter' %>
      </div>

      <div>
        <%= link_to '+ Add an additional transporter', '#', class: 'add-transporter' %>
      </div>

      <div>
        <%= link_to '- Remove transporter', '#', class: 'remove-transporter' %>
      </div>
    </fieldset>

    <div class="designated-facility">
      <fieldset>
        <h3>Designated Facility</h3>
        <%= render 'designated_facility', form: form %>
      </fieldset>
    </div>

    <fieldset>
      <h3>Waste</h3>
      <div class="manifest-items">
        <%= render 'manifest_item' %>
      </div>

      <div>
        <%= link_to '+ Add an additional manifest item', '#', class: 'add-manifest-item' %>
      </div>

      <div>
        <%= link_to '- Remove manifest item', '#', class: 'remove-manifest-item' %>
      </div>
    </fieldset>

    <h3>Other</h3>
    <%= form.input :waste_pcb_description, label: 'PCB description (14)' %>
    <%= form.input :waste_handling_instructions, as: :text, label: 'Special handling instructions and additional information (14)' %>

  <h3>International</h3>
    <%= form.input :international, as: :radio_buttons, label: 'This shipment is international', boolean_style: :inline %>

    <div class="international">
      <%= form.simple_fields_for :international_shipment do |shipment| %>
        <%= shipment.input :export_import, label: 'Import/Export (16)', as: :select, collection: import_options %>
        <%= label_tag :date_leaving_us, 'Date Entering/leaving U.S. (16)' %>
        <%= date_field_tag 'date_leaving_us', nil, name: "manifest[international_shipment][date_leaving_us]" %>
        <%= shipment.simple_fields_for :port_of_entry_exit do |port| %>
          <%= port.input :city, label: 'City of Entry/Exit (16)' %>
          <%= port.input :state, label: 'State of Entry/Exit (16)', collection: us_states %>
        <% end %>
      <% end %>
    </div>

    <%= form.submit 'Continue' %>
  <% end %>

  <h3>DEMONSTRATION PAGE DISCLAIMER </h3>
  <p>This page is only for demonstrations provided by EPA.  EPA is building and providing its services for states and the regulated community to consume first.  At a later time once our services have been built and we have received feedback from states and industry on them, we will build graphical user interfaces for users with input from users that will use those interfaces.</p>
  <h3>DEMONSTRATION PAGE DISCLAIMER </h3>

</div>